spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fund_management
    username: root
    password: huybq
    driver-class-name: com.mysql.cj.jdbc.Driver
  timezone: Asia/Ho_Chi_Minh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 # a week


server:
  version: v1